kind: Service
apiVersion: v1
metadata:
  name: zwave
  namespace: home-assistant
  annotations:
    metallb.universe.tf/address-pool: ip-pool-internal
    metallb.universe.tf/loadBalancerIPs: 192.168.1.237
spec:
  selector:
    app: zwave-js-ui
  ports:
  - port: 3000
    targetPort: 3000
    name: randomport
  - port: 8091
    targetPort: 8091
    name: http
  type: LoadBalancer